# Generated by Django 3.1.3 on 2020-11-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzeria',
            old_name='coordinates',
            new_name='location',
        ),
    ]
